DROP TABLE IF EXISTS dataset_meta;
DROP TABLE IF EXISTS "tws_products";
DROP TABLE IF EXISTS "tws_non_rubber";
DROP TABLE IF EXISTS "ows_open_ear";
DROP TABLE IF EXISTS "iem";
DROP TABLE IF EXISTS "wireless_headphones";
DROP TABLE IF EXISTS "wired_headphones";
DROP TABLE IF EXISTS "dongle_dac";
DROP TABLE IF EXISTS "bluetooth_dac";
DROP TABLE IF EXISTS "eartips";
DROP TABLE IF EXISTS "cables";
DROP TABLE IF EXISTS "desktop_dac";
DROP TABLE IF EXISTS "gaming_headsets";
DROP TABLE IF EXISTS "microphones";
DROP TABLE IF EXISTS "headphone_amps";
DROP TABLE IF EXISTS "stereo_speakers";
DROP TABLE IF EXISTS "bluetooth_speakers";
DROP TABLE IF EXISTS "soundbars";
DROP TABLE IF EXISTS "dap";
DROP TABLE IF EXISTS "soundcards";
DROP TABLE IF EXISTS "wireless_clip_on_mics";
CREATE TABLE IF NOT EXISTS dataset_meta (
  key TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  table_name TEXT NOT NULL,
  columns_json TEXT NOT NULL,
  row_count INTEGER NOT NULL,
  sort_order INTEGER NOT NULL,
  primary_column TEXT,
  price_column TEXT,
  has_slug INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "tws_products" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  name TEXT NOT NULL,
  highlights TEXT,
  tier TEXT,
  price_performance TEXT,
  price_idr REAL,
  microphone_performance TEXT,
  review_summary TEXT,
  bluetooth_codec TEXT,
  battery_life TEXT,
  anc_level TEXT,
  transparency_mode TEXT,
  equalizer_type TEXT,
  overall_sound_score REAL,
  bass_score REAL,
  low_mid_score REAL,
  high_mid_score REAL,
  treble_score REAL,
  vocal_score REAL,
  soundstage_score REAL,
  separation_score REAL,
  imaging_score REAL,
  timbre_score REAL,
  punch_score REAL,
  clarity_score REAL,
  gaming_mode TEXT,
  sound_tuning TEXT,
  ip_rating TEXT,
  multipoint TEXT,
  recommended_eartips TEXT
);
CREATE INDEX IF NOT EXISTS idx_tws_products_tier ON "tws_products" (tier);
CREATE INDEX IF NOT EXISTS idx_tws_products_score ON "tws_products" (overall_sound_score);
CREATE TABLE IF NOT EXISTS "tws_non_rubber" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "value_for_money" TEXT,
  "sound" TEXT,
  "tws" TEXT,
  "price" TEXT,
  "review_notes" TEXT,
  "bluetooth_codec" TEXT,
  "battery_life_no_anc" TEXT,
  "anc_performance_db" TEXT,
  "transparency_adjustable" TEXT,
  "equalizer" TEXT,
  "bass" TEXT,
  "lo_mid" TEXT,
  "hi_mid" TEXT,
  "treble" TEXT,
  "vocal" TEXT,
  "technicality" TEXT,
  "driver" TEXT,
  "overall" TEXT,
  "gaming_modre_low_latency" TEXT,
  "sound_tuning" TEXT,
  "ip_rating" TEXT,
  "multipoint_connection" TEXT
);
CREATE TABLE IF NOT EXISTS "ows_open_ear" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "value_for_money" TEXT,
  "tws" TEXT,
  "price" TEXT,
  "bentuk" TEXT,
  "review_notes" TEXT,
  "fitting" TEXT,
  "battery_life" TEXT,
  "ip_rating" TEXT
);
CREATE TABLE IF NOT EXISTS "iem" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "value" TEXT,
  "sound" TEXT,
  "iem" TEXT,
  "price" TEXT,
  "kabel" TEXT,
  "musician_monitor_fit" TEXT,
  "percentage" TEXT,
  "driver" TEXT,
  "review_notes" TEXT,
  "total_sound" TEXT,
  "bass" TEXT,
  "lo_mid" TEXT,
  "hi_mid" TEXT,
  "treble" TEXT,
  "voc" TEXT,
  "sibilance" TEXT,
  "soundstage" TEXT,
  "imaging" TEXT,
  "instrument_separation" TEXT,
  "timbre" TEXT,
  "punch" TEXT,
  "detail" TEXT,
  "multidriver_subjective" TEXT,
  "linearity" TEXT,
  "recommended_eartips" TEXT,
  "kabel_recommend" TEXT,
  "parametric_eq" TEXT
);
CREATE TABLE IF NOT EXISTS "wireless_headphones" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "value_4_money" TEXT,
  "tier" TEXT,
  "headphone_video_review" TEXT,
  "price" TEXT,
  "review_notes" TEXT,
  "bass" TEXT,
  "lo_mid" TEXT,
  "hi_mid" TEXT,
  "treble" TEXT,
  "voc" TEXT,
  "technicality" TEXT,
  "driver_quality" TEXT,
  "overall_sound" TEXT,
  "anc" TEXT,
  "transparancy" TEXT,
  "tuning" TEXT,
  "codec" TEXT,
  "battery_life" TEXT,
  "eq" TEXT,
  "overall_comfort" TEXT,
  "rasa_jepit_samping" TEXT,
  "rasa_nyaman_headband" TEXT,
  "ruang_lingkar_pads" TEXT,
  "multipoint_connection" TEXT,
  "driver" TEXT,
  "gaming_mode" TEXT,
  "cable_mode" TEXT
);
CREATE TABLE IF NOT EXISTS "wired_headphones" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "rank" TEXT,
  "headphone" TEXT,
  "price" TEXT,
  "needs" TEXT,
  "review_notes" TEXT,
  "type" TEXT,
  "bass" TEXT,
  "lo_mid" TEXT,
  "hi_mid" TEXT,
  "treble" TEXT,
  "voc" TEXT,
  "technicality" TEXT,
  "driver_quality" TEXT,
  "earpads" TEXT,
  "fitting" TEXT,
  "tuning" TEXT,
  "driver_type" TEXT,
  "impedance_dan_sensitivity" TEXT
);
CREATE TABLE IF NOT EXISTS "dongle_dac" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "tier" TEXT,
  "value" TEXT,
  "dac" TEXT,
  "price" TEXT,
  "connector_type" TEXT,
  "output_interface" TEXT,
  "power_source" TEXT,
  "chip" TEXT,
  "sound_description" TEXT,
  "subjective_sound_rating" TEXT,
  "dynamics" TEXT,
  "punch" TEXT,
  "clarity_detail" TEXT,
  "soundstage_openness" TEXT,
  "instrument_separation" TEXT,
  "analog_vs_digital_character" TEXT,
  "power" TEXT,
  "review_notes" TEXT,
  "bluetooth_features" TEXT,
  "microphone_input" TEXT,
  "needs_amp_stacking" TEXT
);
CREATE TABLE IF NOT EXISTS "bluetooth_dac" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "value" TEXT,
  "dac" TEXT,
  "price" TEXT,
  "connector_type" TEXT,
  "output_interface" TEXT,
  "power_source" TEXT,
  "chip" TEXT,
  "sound_description" TEXT,
  "subjective_sound_rating" TEXT,
  "dynamics" TEXT,
  "punch" TEXT,
  "clarity_detail" TEXT,
  "soundstage_openness" TEXT,
  "instrument_separation" TEXT,
  "analog_vs_digital_character" TEXT,
  "power" TEXT,
  "review_notes" TEXT,
  "bluetooth_features" TEXT,
  "microphone_input" TEXT,
  "needs_amp_stacking" TEXT
);
CREATE TABLE IF NOT EXISTS "eartips" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "rank" TEXT,
  "eartips" TEXT,
  "price" TEXT,
  "dipakai_di" TEXT,
  "karakter" TEXT,
  "pernah_dipakai_di" TEXT
);
CREATE TABLE IF NOT EXISTS "cables" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "rank" TEXT,
  "kabel" TEXT,
  "price" TEXT,
  "tiktok" TEXT,
  "mic_mic_test" TEXT,
  "konektor_iem" TEXT,
  "konektor_device" TEXT,
  "bahan" TEXT,
  "notes" TEXT,
  "jack_option" TEXT
);
CREATE TABLE IF NOT EXISTS "desktop_dac" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "value_rank" TEXT,
  "dac" TEXT,
  "price" TEXT,
  "digital_input" TEXT,
  "output_interface" TEXT,
  "pure_dac_or_dac_amp" TEXT,
  "chip" TEXT,
  "sound_description" TEXT,
  "subjective_sound_rating" TEXT,
  "dynamics" TEXT,
  "punch" TEXT,
  "clarity_detail" TEXT,
  "soundstage_openness" TEXT,
  "instrument_separation" TEXT,
  "analog_digital" TEXT,
  "review_notes" TEXT,
  "bluetooth_features" TEXT
);
CREATE TABLE IF NOT EXISTS "gaming_headsets" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "rank" TEXT,
  "headphone" TEXT,
  "type" TEXT,
  "price" TEXT,
  "review_notes" TEXT,
  "bass" TEXT,
  "lo_mid" TEXT,
  "hi_mid" TEXT,
  "treble" TEXT,
  "voc" TEXT,
  "technicality" TEXT,
  "driver_quality" TEXT,
  "fitting" TEXT,
  "tuning" TEXT,
  "microphone" TEXT,
  "wireless_capability" TEXT,
  "spatial_surround" TEXT,
  "app" TEXT,
  "eq" TEXT
);
CREATE TABLE IF NOT EXISTS "microphones" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "rank" TEXT,
  "microphone" TEXT,
  "price" TEXT,
  "shopee_tiktok" TEXT,
  "type_capsule" TEXT,
  "connection" TEXT,
  "needs" TEXT,
  "review_notes" TEXT,
  "polar_pattern" TEXT,
  "dipakenya_gini_nih_blay" TEXT
);
CREATE TABLE IF NOT EXISTS "headphone_amps" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "rank" TEXT,
  "headphone_amp" TEXT,
  "price" TEXT,
  "input" TEXT,
  "output_interface" TEXT,
  "feature" TEXT,
  "review_notes" TEXT
);
CREATE TABLE IF NOT EXISTS "stereo_speakers" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "value" TEXT,
  "speaker" TEXT,
  "price" TEXT,
  "needs" TEXT,
  "posisi_dengerin" TEXT,
  "type" TEXT,
  "fitur_dan_review" TEXT,
  "saran_subwoofer" TEXT,
  "connection" TEXT,
  "bluetooth" TEXT,
  "additional_feature" TEXT,
  "sub_out" TEXT,
  "headphone_out" TEXT,
  "soundtest" TEXT
);
CREATE TABLE IF NOT EXISTS "bluetooth_speakers" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "value_4_money" TEXT,
  "price" TEXT,
  "price_1" TEXT,
  "speaker" TEXT,
  "price_2" TEXT,
  "price_3" TEXT,
  "fitur_dan_review" TEXT,
  "size" TEXT,
  "mobile_friendly" TEXT,
  "connection" TEXT,
  "bluetooth" TEXT,
  "stereo_mode" TEXT,
  "battery_life" TEXT,
  "ip_rating" TEXT,
  "soundtest" TEXT,
  "additional_feature" TEXT
);
CREATE TABLE IF NOT EXISTS "soundbars" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "rank" TEXT,
  "speaker" TEXT,
  "price" TEXT,
  "unit" TEXT,
  "fitur_dan_review" TEXT,
  "immersive_audio_virtualisation" TEXT,
  "wired_connect" TEXT,
  "wireless_connect" TEXT,
  "app_support" TEXT,
  "sub_connect" TEXT
);
CREATE TABLE IF NOT EXISTS "dap" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "dap" TEXT,
  "price" TEXT,
  "android_yes_no" TEXT,
  "output_interface" TEXT,
  "dac_chip" TEXT,
  "battery_life" TEXT,
  "bluetooth_transmitter" TEXT,
  "bluetooth_receiver" TEXT,
  "notes" TEXT,
  "notes_1" TEXT
);
CREATE TABLE IF NOT EXISTS "soundcards" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "rank" TEXT,
  "soundcard" TEXT,
  "price" TEXT,
  "input_output" TEXT,
  "review_notes" TEXT,
  "varian_dengan_jumlah_input_lainnnya" TEXT
);
CREATE TABLE IF NOT EXISTS "wireless_clip_on_mics" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_order INTEGER NOT NULL,
  slug TEXT,
  "rank" TEXT,
  "microphone" TEXT,
  "price" TEXT,
  "connection" TEXT,
  "review_notes" TEXT,
  "signal_to_noise_ratio" TEXT,
  "sound_pressure_level" TEXT,
  "noise_cancellation" TEXT,
  "dipakenya_gini_nih_blay" TEXT
);